/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const UserInfo = IDL.Record({
  'fullName' : IDL.Text,
  'village' : IDL.Text,
  'mobile' : IDL.Text,
  'validUntil' : IDL.Opt(IDL.Text),
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'village' : IDL.Text,
    'mobile' : IDL.Text,
    'validUntil' : IDL.Opt(IDL.Text),
  }),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteUser' : IDL.Func([IDL.Text], [RegisterResult], []),
  'getUserInfo' : IDL.Func([IDL.Text], [IDL.Opt(UserInfo)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'removeUserValidity' : IDL.Func([IDL.Text], [RegisterResult], []),
  'setUserValidity' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'updatePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'updateUserInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RegisterResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserInfo = IDL.Record({
    'fullName' : IDL.Text,
    'village' : IDL.Text,
    'mobile' : IDL.Text,
    'validUntil' : IDL.Opt(IDL.Text),
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({
      'role' : IDL.Text,
      'fullName' : IDL.Text,
      'village' : IDL.Text,
      'mobile' : IDL.Text,
      'validUntil' : IDL.Opt(IDL.Text),
    }),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteUser' : IDL.Func([IDL.Text], [RegisterResult], []),
    'getUserInfo' : IDL.Func([IDL.Text], [IDL.Opt(UserInfo)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'removeUserValidity' : IDL.Func([IDL.Text], [RegisterResult], []),
    'setUserValidity' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'updatePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'updateUserInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };