/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type LoginResult = {
    'ok' : {
      'role' : string,
      'fullName' : string,
      'village' : string,
      'mobile' : string,
      'validUntil' : [] | [string],
    }
  } |
  { 'err' : string };
export type RegisterResult = { 'ok' : null } |
  { 'err' : string };
export interface UserInfo {
  'fullName' : string,
  'village' : string,
  'mobile' : string,
  'validUntil' : [] | [string],
}
export interface _SERVICE {
  'deleteUser' : ActorMethod<[string], RegisterResult>,
  'getUserInfo' : ActorMethod<[string], [] | [UserInfo]>,
  'listAllUsers' : ActorMethod<[], Array<UserInfo>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'register' : ActorMethod<[string, string, string, string], RegisterResult>,
  'removeUserValidity' : ActorMethod<[string], RegisterResult>,
  'setUserValidity' : ActorMethod<[string, string], RegisterResult>,
  'updatePassword' : ActorMethod<[string, string, string], RegisterResult>,
  'updateUserInfo' : ActorMethod<[string, string, string], RegisterResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];